# Generated by Django 5.1.3 on 2024-11-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_leaderboard_updated_at_leaderboard_rank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('coach', models.CharField(max_length=100)),
                ('ranking', models.IntegerField()),
                ('year_founded', models.IntegerField()),
                ('points', models.IntegerField(default=10)),
            ],
        ),
    ]
