# Generated by Django 5.1.3 on 2024-11-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.CharField(default='McMahon Stadium', max_length=255),
        ),
    ]
