# Generated by Django 5.1.3 on 2024-11-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_match_stadium'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_odds',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_odds',
            field=models.FloatField(default=1.0),
        ),
    ]
